version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22

  build:
    commands:
      - echo "Instalando dependencias..."
      - go get -t -v ./...
      - echo "Ejecutando pruebas..."
      - go test . -coverprofile coverage-report
      - go tool cover -html coverage-report -o coverage-report.html
      - go install github.com/jstemmer/go-junit-report/v2@latest
      - go test -v 2>&1 . | go-junit-report -set-exit-code > reports/report.xml
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.57.2
      - golangci-lint run
      - echo "Compilando la aplicación..."
      - go build -o application

reports:
  coverage-report:
    files:
      - 'coverage-report.html'
    file-format: 'HTML'
  junit-report:
    files:
      - 'reports/report.xml'
    file-format: 'JUNITXML'

artifacts:
  files:
    - application