version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22

  build:
    commands:
      - echo "Instalando dependencias..."
      - go get -t -v ./...
      - echo "Compilando la aplicación..."
      - go build -o application
      - echo "Ejecutando pruebas..."
      - go test -v ./... -coverprofile cover.out

  post_build:
    commands:
      - echo "Empaquetando la aplicación..."
      # Puedes agregar comandos adicionales aquí si es necesario

reports:
  CoverageReport:
    files:
      - 'cover.out'
    file-format: 'CLOVERXML'
    # Debes asegurarte de convertir el reporte de cobertura de Go al formato esperado si es necesario
    # Go no soporta directamente el formato CLOVERXML; esto es solo un ejemplo y puede necesitar adaptación

artifacts:
  files:
    - application
  # Asegúrate de que los nombres y ubicaciones de los archivos coincidan con lo que tu aplicación genera y necesita
