version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
    commands:
      - echo "Instalando dependencias..."
      - go get -t -v ./...
      - go install github.com/jstemmer/go-junit-report/v2@latest
      #- go install github.com/t-yuki/gocover-cobertura@latest
      - go get github.com/boumenot/gocover-cobertura

  build:
    commands:
      - echo "Ejecutando pruebas y generando reportes..."
      #- go test -coverprofile coverage-report.out
      #- go tool cover -html=coverage-report.html -o coverage-report.html
      #- go tool cover -func=coverage-report.out -o coverage-report.txt
      #- gocover-cobertura < coverage-report.out > coverage-report.xml
      - go test -coverprofile=coverage.txt -covermode count github.com/gorilla/mux
      - gocover-cobertura < coverage.txt > coverage.xml
      - go test -v 2>&1 | go-junit-report -set-exit-code > reports/report.xml
      - echo "Compilando la aplicación..."
      - go build -o application

reports:
  coverage-report:
    files:
      - 'coverage-report.xml'  # Cobertura XML format compatible with AWS Beanstalk
    file-format: 'COBERTURAXML'
  junit-report:
    files:
      - 'reports/report.xml'
    file-format: 'JUNITXML'

artifacts:
  files:
    - application