version: 0.2

env:
  variables:
    GO111MODULE: "off"

phases:
  install:
    runtime-versions:
      golang: 1.22
    commands:
      - go get -t -v ./...

  pre_build:
    commands:
      - echo "Ejecutando pruebas..."
      - go test . -coverprofile coverage-report
      - go tool cover -html coverage-report -o coverage-report.html
      - go install github.com/jstemmer/go-junit-report/v2@latest
      - go test -v 2>&1 . | go-junit-report -set-exit-code > reports/report.xml
  build:
    commands:
      - echo "Instalando dependencias..."
      - echo "Compilando la aplicación..."
      - go build -o application

reports:
  coverage-report:
    files:
      - 'coverage-report.html'
    file-format: 'HTML'
  junit-report:
    files:
      - 'reports/report.xml'
    file-format: 'JUNITXML'

artifacts:
  files:
    - application